dist: trusty
language: python

script:
    - git clone https://github.com/statoil/segyio
    - git clone https://github.com/statoil/libecl
    - mkdir segyio-build libecl-build
    - pushd segyio-build
    - cmake $TRAVIS_BUILD_DIR/segyio
            -DBUILD_PYTHON=ON
            -DCMAKE_MODULE_PATH=$TRAVIS_BUILD_DIR
            -DCMAKE_INSTALL_PREFIX=`pwd`
    - make -j2 install
    - popd
    - pushd libecl-build
    - cmake $TRAVIS_BUILD_DIR/libecl
            -DBUILD_PYTHON=ON
            -DCMAKE_MODULE_PATH=$TRAVIS_BUILD_DIR
            -DCMAKE_INSTALL_PREFIX=`pwd`
    - make -j2 install
    - popd
